<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="robotModel" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value=".4" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.06" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value=".1397" /> <!-- Link 1 -->
  <xacro:property name="height2" value="0.32476" /> <!-- Link 2 -->
  <xacro:property name="height3" value="0.28416" /> <!-- Link 3 -->
  <xacro:property name="height4" value="0.12065" /> <!-- Link 0 -->
  <xacro:property name="axel_offset" value="${.060325/2}" /> 

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find IRAC)/urdf/robotModel.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find IRAC)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <!-- Link 1 || BASE -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <mesh filename="$(find IRAC)/urdf/meshes/Base.stl" scale=".001 .001 .001"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <mesh filename="$(find IRAC)/urdf/meshes/Base.stl" scale=".001 .001 .001"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	      ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	      iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	      izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <!-- JOINT 1 -->
  <joint name="joint1" type="continuous">
    <parent link="world"/>
    <child link="link1"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
    <!-- <limit lower="${-PI/2}" upper="${PI/2}" effort="30.0" velocity="10.0"/> -->
  </joint>

  <!-- Link 2 -->
  <link name="link2">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <mesh filename="$(find IRAC)/urdf/meshes/Link1.stl" scale=".001 .001 .001"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <mesh filename="$(find IRAC)/urdf/meshes/Link1.stl" scale=".001 .001 .001"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	      ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
	      iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
	      izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <!-- JOINT 2 -->
  <joint name="joint2" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 ${-1*axel_offset} .127175" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <!-- <limit lower="${-PI/2}" upper="${PI/2}" effort="30.0" velocity="10.0"/> -->
  </joint>

  <!-- Link 3 -->
  <link name="link3">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <mesh filename="$(find IRAC)/urdf/meshes/Link2.stl" scale=".001 .001 .001"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <mesh filename="$(find IRAC)/urdf/meshes/Link2.stl" scale=".001 .001 .001"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	      ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
	      iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
	      izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <!-- JOINT 3 -->
  <joint name="joint3" type="continuous">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 0 .28076" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <!-- <limit lower="${-PI/2}" upper="${PI/2}" effort="30.0" velocity="10.0"/> -->
  </joint>

  <!-- LINK 4-->
  <link name="link4">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <mesh filename="$(find IRAC)/urdf/meshes/Link3.stl" scale=".001 .001 .001"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <mesh filename="$(find IRAC)/urdf/meshes/Link3.stl" scale=".001 .001 .001"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	      ixx="${mass / 12.0 * (width*width + height4*height4)}" ixy="0.0" ixz="0.0"
	      iyy="${mass / 12.0 * (height4*height4 + width*width)}" iyz="0.0"
	      izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <!-- JOINT 4 -->
  <joint name="joint4" type="continuous">
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="0 .05237 .25975" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
    <!-- <limit lower="${-PI/2}" upper="${PI/2}" effort="30.0" velocity="10.0"/> -->
  </joint>

  <!-- GAZEBO ROS CONTROL SPECIFIC INFORMATION -->
  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint4">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor4">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


<!-- END OF ROBOT -->
</robot>
